### ISSUE TITLE
Needs consistent classes for blocks

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/imageblock#1]
I created one block and the class it assigned was: `block-imageblock-default`. Instead of the machine name at the end it just has "default". The second block I created in the same region had the proper class.

**Comment by herbdool** [comment]
I think the second block worked because I had first added it to a different layout. So once it was added a second time in a different layout it had the proper class.

I recommend always using the machine name instead of "default" so that CSS can be properly targeted.

**Comment by indigoxela** [comment]
@herbdool that behavior is intentionally.

It's necessary to make image blocks reusable.

**Comment by indigoxela** [comment]
Ah, wait, now I get it: you're talking about the css class... ;-)

I'll dig into this soon.

**Comment by indigoxela** [comment]
The [latest commit](https://github.com/backdrop-contrib/imageblock/commit/146dac59cbbeb18990e5492c035353574beba06e) brings the feature you're after: an additional css class based on machine name for imageblocks with default delta.

Please test.

**Comment by herbdool** [comment]
@indigoxela thanks. Yeah, it's more of an enhancement, though seems pretty necessary for CSS.

**Comment by herbdool** [comment]
That helps:

![Screenshot from 2019-12-20 10-43-50](https://user-images.githubusercontent.com/1071483/71266132-bff4d380-2315-11ea-8437-d7c816854410.png)

I thought I'd compare it with Custom Blocks (some of my comments below might be considered new features):

![Screenshot from 2019-12-20 10-46-33](https://user-images.githubusercontent.com/1071483/71266344-30035980-2316-11ea-84af-e7b23215955d.png)

Custom blocks keeps the same css classes for each instance of the block. Plus they have the same machine name. They're the same block, just instances. And editing the block changes all instances. (Though it's glitchy too but that's a different story). Since they have the same css classes it's easy to style them all.

As for imageblock each block needs to be a unique machine_name. I guess that's neither good nor bad, though it does make styling a group of them. For example, if I want to add the same image in the header to *all* layouts, it's not easy to do with imageblock. Whereas with custom block it's easy. And I can update them all at the same time. Plus they all have the same CSS classes.

**Comment by indigoxela** [comment]
So you ask for a common class for all image blocks now, right?

Would "block-image" for all of them be sufficient?

**Comment by herbdool** [comment]
I'm not sure what's best.

I think what I'd like is a way of having a common css class for the "group" of related blocks, like what custom block does. Though it looks like it's not possible with image block since it creates a new delta every time the same block is added.

**Comment by indigoxela** [comment]
> I think what I'd like is a way of having a common css class for the "group" of related blocks

That's the point. Imageblock has no "groups" at all. Implementing it would require a rewrite.
If you need some sort of grouping for css, you could add css classes via the layout form.

**Comment by indigoxela** [comment]
The [latest commit](https://github.com/backdrop-contrib/imageblock/commit/7a9dc5b18ec513776fe1002efe2646d9df90ffa0) provides a common css class for all image blocks.

You can now create selectors like:
`.l-header .block-imageblock` to add special css rules if image blocks are in a certain region.

I know, that's not exactly the solution you're after. But at least it helps to style imageblocks depending on their parent region.

**Comment by indigoxela** [comment]
@herbdool the new release (1.x-1.0.4) contains both css class additions. I'm not sure, if I can do more for you. If you have an idea, please let me know.

**Comment by indigoxela** [comment]
Closing this in favor of the follow-up issue.
