### ISSUE TITLE
Unable to find option to make image block reusable.

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/imageblock#11]
I see there is a closed issue #6 where another user had trouble finding the option to make an image block reusable and then they found it but did not explain how or where. I am having the same problem. The only place to create a new image block is through a layout, when managing the layout and adding a block, selecting image block. When I go through all the dialog options I do not see the option to make the block reusable when the js aggregation is either on or off. Any help in locating the option is appreciated. Thank you.

**Comment by indigoxela** [comment]
> finding the option to make an image block reusable

All image blocks are reusable by default. That's built-in. :smile_cat:

You get an overview of all existing image blocks in this admin listing: admin/structure/imageblock/list (Structure / Image blocks).

There you can delete obsolete image blocks (if not in use anymore).

**Comment by izmeez** [comment]
Maybe I am doing something wrong. I have created an image block in a mini layout and when I then add the image block to another layout, for example in a sidebar, I am required to give it another admin name and I then end up with double the number of image blocks. If I then update the configuration in one, for example the title in the mini-layout image block it does not change the title of the corresponding block in the sidebar.

I saw the discussion in issue #2 but didn't understand how it addresses what I'm trying to do. I would just like to have a single image block that I can use in different layouts and changes to it are seen everywhere because there's only one.

It would also be nice if the admin/structure/imageblock/list had an option to add an image block.

**Comment by izmeez** [comment]
I did wonder if I should instead just create a custom block with an image and paused when I saw that the images in the imageblocks I had created were now in a subdirectory with their own styles and I would have to upload the images again into the normal file system. Just paused to think about it. I used image block in Drupal and it was convenient. Since it's a rebuild in BD and not a migration I could approach it differently. Trying to weigh the advantages and disadvantages.

**Comment by indigoxela** [comment]
I don't think you'll achieve what you want with blocks. That's not how they work.

If I may suggest something: use a node type, if you want a "thing", that's the same in every layout.
Just a content type with a hidden path.

**Comment by izmeez** [comment]
I like imageblock I would just like to avoid creating duplicate entries, although I think it is only one imageblock that then has a dependency.

**Comment by izmeez** [comment]
My tests confirm I can use custom blocks to achieve the same result as image block without duplicate blocks. I think I will push that envelope and see how far it takes me. Thanks.

**Comment by indigoxela** [comment]
Sure, whatever works best for your use-case, glad you sorted things out! :+1:
