### ISSUE TITLE
Change package type capitalisation in .info file

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/imageblock#4]
https://github.com/albanycomputers/imageblock/tree/patch-1

The .info file has the package as: -

package = User interface

It should be

package = User Interface

The above leads to two "User Interface" options when using the "Module Filter" module.

See the documentation at https://docs.backdropcms.org/creating-modules

"Capitalization is important because package string is case sensitive and using package = fields in one module and package = Fields in another would yield two different packages on the module administration page. This can be highly confusing as Seven (the default administrative theme) capitalizes fieldset legends, making fields and Fields indistinguishable. Using package = Fields is the correct way."

**Comment by indigoxela** [comment]
Many thanks, merged :+1:
