### ISSUE TITLE
Add support for SVG files

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/imageblock#7]
Please can this module support SVG files?
Perhaps it just needs adding to the list of existing extensions or perhaps it needs something extra like the code that added `webp`?

**Comment by indigoxela** [comment]
Interesting idea, never tried that.

The derivative handling (image styles) might be a problem.

**Comment by indigoxela** [comment]
@yorkshire-pudding in fact, this seems feasible. A [PR](https://github.com/backdrop-contrib/imageblock/pull/8) is available for testing.

Be warned, written quickly and it probably still has bugs.

**Comment by yorkshire-pudding** [comment]
Thanks @indigoxela - I'll give it a test this evening

**Comment by yorkshire-pudding** [comment]
Thanks @indigoxela - I've tested this PR and it looks really good.

**Comment by indigoxela** [comment]
@yorkshire-pudding many thanks for testing, after a little change the PR has been merged.

Want to give the latest dev a final test?

**Comment by yorkshire-pudding** [comment]
@indigoxela - tested the latest dev.  Added several svgs to a layout and gave them each a different size.  All worked well.
Thank you for such a speedy resolution to my request.
