### ISSUE TITLE
[UX] Make clearer how to create blocks

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/imageblock#9]
Using the module for the first time, it is not completely intuitive how to add new blocks.  The presence on the menu of an Image blocks page could make people (e.g. me) look there and wonder why can't create one.

I therefore propose to add a few bullet points to the Readme, and an additional note to the admin page.
PR to follow

**Comment by indigoxela** [comment]
@yorkshire-pudding that's a good idea! Many thanks for your PR.
